"""Agent-prepared continuations retain lineage across actual tool-calling chat turns."""

import json
from pathlib import Path

import pytest

from conjecture_solver.research_service import ResearchService, put
from conjecture_solver.web.application import SimjectureWebApplication
from tests.test_workspace import connect, wait_for
from tests.test_workspace import provider as protocol_provider


@pytest.fixture
def provider():
    yield from protocol_provider.__wrapped__()


def test_agent_prepares_continuation_without_launch_and_preserves_parent(tmp_path, provider):
    app = SimjectureWebApplication(runs_root=tmp_path / "runs", scan_roots=(tmp_path,))
    connect(app.workspace, provider[0])
    parent = ResearchService.create(tmp_path / "parent", "Investigate energy conversion")
    parent.freeze_protocol("Measure boundary flux independently.")
    (parent.work / "calculation.py").write_text("print(1)\n")
    (parent.work / "reader.py").write_text("print(2)\n")
    parent.manifest["capabilities"] = str(tmp_path / "installed-instruments")
    put(parent.root / "research.json", parent.manifest)
    before = (parent.root / "research.json").read_bytes()
    token = app.registry.register(parent.root)
    result = app.workspace.prepare_continuation(
        {
            "campaign": token,
            "approach": "agent",
            "guidance": "",
            "hours": 3,
            "files": ["calculation.py"],
        },
        app,
    )
    assert result["view"] == "interactive"
    identifier = result["project"]
    project = wait_for(
        lambda: (
            (p if not p["running"] else None) if (p := app.workspace.project(identifier)) else None
        )
    )
    assert project["brief"]  # Generated by the real draft_study tool, not prepare_continuation.
    assert project["brief"]["capability_directory"] == parent.manifest["capabilities"]
    assert not project["studies"]
    assert project["continuation_draft"]["parent"] == str(parent.root)
    context = json.loads(
        (
            Path(project["files_directory"]) / project["continuation_draft"]["context_file"]
        ).read_text()
    )
    assert context["original_question"] == parent.manifest["hypothesis"]
    assert context["proposed_hours"] == 3
    assert context["selected_files"] == ["calculation.py"]
    assert "Worker notes are unreviewed" in context["authority"]
    # Further conversation preserves the parent context through resumed sessions.
    app.workspace.send(identifier, {"message": "Refine the plan using axial structure."})
    project = wait_for(
        lambda: (
            (p if not p["running"] else None) if (p := app.workspace.project(identifier)) else None
        )
    )
    assert project["continuation_draft"]["parent"] == str(parent.root)
    prompts = [
        p.read_text() for p in app.workspace.directory(identifier).glob("turns/*/prompt.txt")
    ]
    assert len(prompts) == 2
    assert all("CONTINUATION PREPARATION" in p and str(parent.root) in p for p in prompts)
    # Agent-selected files are constrained to the original parent's research workspace.
    brief = project["brief"] | {"inherited_files": ["calculation.py", "reader.py"]}
    app.workspace.save_brief(identifier, brief)
    assert app.workspace.project(identifier)["continuation_draft"]["files"] == [
        "calculation.py",
        "reader.py",
    ]
    with pytest.raises(ValueError):
        app.workspace.save_brief(identifier, brief | {"inherited_files": ["../private.json"]})
    assert (parent.root / "research.json").read_bytes() == before


def test_direct_draft_can_be_discussed_with_agent(tmp_path, provider):
    app = SimjectureWebApplication(runs_root=tmp_path / "runs", scan_roots=(tmp_path,))
    connect(app.workspace, provider[0])
    parent = ResearchService.create(tmp_path / "parent", "Q")
    token = app.registry.register(parent.root)
    result = app.workspace.prepare_continuation(
        {"campaign": token, "guidance": "Resolve 3D effects", "hours": 2}, app
    )
    identifier = result["project"]
    app.workspace.prepare(identifier, {"approach": "continuation"})
    project = wait_for(
        lambda: (
            (p if not p["running"] else None) if (p := app.workspace.project(identifier)) else None
        )
    )
    assert project["brief"] and not project["studies"]
    assert project["continuation_draft"]["guidance"] == "Resolve 3D effects"


def test_missing_model_keeps_recoverable_chat_preparation(tmp_path, monkeypatch):
    app = SimjectureWebApplication(runs_root=tmp_path / "runs", scan_roots=(tmp_path,))
    monkeypatch.setattr(
        app.workspace,
        "project_connection",
        lambda _: (_ for _ in ()).throw(ValueError("Choose a model")),
    )
    parent = ResearchService.create(tmp_path / "parent", "Q")
    result = app.workspace.prepare_continuation(
        {"campaign": app.registry.register(parent.root), "approach": "agent"}, app
    )
    assert result["view"] == "interactive"
    assert result["preparation_error"]
    project = app.workspace.project(result["project"])
    assert project["continuation_draft"] and not project["brief"] and not project["running"]
